"""Versioned LLM prompt templates for Rabbit Hole Mapper."""

from .prompts import (
    CLAIM_EXTRACTION_V1,
    CONTRADICTION_ADJUDICATION_V1,
    DEVIL_ADVOCATE_V1,
    ENTITY_RESOLUTION_V1,
    NARRATOR_V1,
    QUERY_EXPANSION_V1,
    TEMPORAL_EXTRACTION_V1,
)

__all__ = [
    "QUERY_EXPANSION_V1",
    "CLAIM_EXTRACTION_V1",
    "ENTITY_RESOLUTION_V1",
    "CONTRADICTION_ADJUDICATION_V1",
    "TEMPORAL_EXTRACTION_V1",
    "NARRATOR_V1",
    "DEVIL_ADVOCATE_V1",
]
